
server:
  port: 8080

spring:
  datasource:
    username: shao
    password: 123456
    url: jdbc:mysql://localhost:3306/shao?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.shao.wacky.entity

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  typeAliasesPackage: com.shao.wacky.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#log

#showSql
logging:
  level:
    com:
      shao:
        wacky:
          mapper : debug
  config: classpath:logback.xml


